server:
  port: 8080
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  messages:
    basename: messages
  application:
    name: my-restful-service
#  security:
#    user:
#      name: username
#      password: passw0rd
logging:
  level:
    org.springframework: debug
management:
  endpoints:
    web:
      exposure:
        include: "*"