server:
  port: 8080
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  messages:
    basename: messages
  application:
    name: my-restful-service
  datasource:
    url: jdbc:h2:tcp://localhost/~/test
    username: sa
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    defer-datasource-initialization: true
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
  sql:
    init:
      mode: always
      data-locations: classpath:data.sql # -> data.sql을 서버 시작할 때 실행 시킬 수 있게 함

#  security:
#    user:
#      name: username
#      password: passw0rd
logging:
  level:
    org.springframework: debug
management:
  endpoints:
    web:
      exposure:
        include: "*"